---

- name: ensure ntp package is absent
  package: name=ntp state=absent

- name: install chrony
  package:
    name: ["chrony", "tzdata"]
    state: present

- name: set timezone to etc/utc
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: true

- name: set chrony configuration
  template: src=templates/chrony.conf.j2 dest=/etc/chrony.conf owner=root group=root mode=0644
  notify:
    - chronyd restart

- name: ensure that chronyd is running
  service: name=chronyd state=started enabled=yes
  when: not ntp_role_debug|bool
