---
- name: ntp daemon-reload
  when: not ntp_role_debug|bool
  ansible.builtin.systemd:
    daemon_reload: true

- name: ntp enable
  when: not ntp_role_debug|bool
  ansible.builtin.service:
    name: chronyd
    enabled: true
